# Generated by Django 4.2.3 on 2023-08-02 00:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="countryItMade",
            field=models.CharField(default="USA", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="car",
            name="model",
            field=models.CharField(default="RC F", max_length=100),
            preserve_default=False,
        ),
    ]
