# Generated by Django 4.2.3 on 2023-08-06 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main_app", "0002_car_countryitmade_car_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="Insurance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("policyNumber", models.IntegerField()),
                ("provider", models.CharField(max_length=100)),
                ("coverageAmount", models.IntegerField()),
                ("startDate", models.DateField(verbose_name="Starting Date")),
                ("endDate", models.DateField(verbose_name="Ending Date")),
                (
                    "car",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main_app.car"
                    ),
                ),
            ],
        ),
    ]
